name: Yeller
main: com.GeForce.G_4sYeller.G_4sYeller
version: 1.0

commands:
    yell:
        usage: /yell [title](*SPACE* , *SPACE* [subtitle])
        usage: /yell [subtitle] -t
        permission: G_4sYeller.yell
        permission-message: You don't have <permission>
        description: This command yells in form of a title.
permissions:
    Yeller.yell:
        description: Gives permission to the yell command.
        